### ISSUE TITLE
Command google returned: Error: [WinError 10060]

### ISSUE THREAD

**Issue by Sean19899999** [Torantulino/Auto-GPT#1041]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Internet connection: Using a proxy running on V2rayN

**python scripts/main.py**

Welcome back!  Would you like me to return to being ResearchGPT?
Continue with the last settings?
Name:  ResearchGPT
Role:   an AI designed to autonomously search articles and write a paper of "abalone heterosis"
Goals: ['write a 1000 words article, use latest articles, write like an expert, include citation information and reference list in the article']
Continue (y/n): n
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: ResearchGPT
ResearchGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
ResearchGPT is: an AI designed to autonomously search articles and write a paper of "abalone heterosis"
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1:  write a 1000 words article
Goal 2:  use latest articles
Goal 3: write like an expert
Goal 4: include citation information and reference list in the article
Goal 5:
Using memory of type: PineconeMemory
RESEARCHGPT THOUGHTS:  To write an article on abalone heterosis, I need to first gather information. The best way to do that is to search Google for recent articles. After that, I can read through those articles and take note of important information that I will use in writing my article. I will use the 'google' command to search for recent articles.
REASONING:  I need to begin by gathering relevant information before proceeding with my writing. Google is the best search engine for finding recent articles on any topic, therefore I will start by conducting a Google search on 'abalone heterosis'.
PLAN:
-  Use the 'google' command to search 'abalone heterosis'.
-  Read through the resulting articles and take notes on important information.
-  write article based on gathered information.
-  Review and refine writing.
-  Submit article for evaluation.
-  Critically evaluate performance.
CRITICISM:  I did not consider other search engines besides Google. I need to make sure I weigh all factors when considering which search engine to use for a particular search.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'abalone heterosis'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ResearchGPT...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=

**SYSTEM:  Command google returned: Error: [WinError 10060]** 

### Current behavior 😯

Stuck on repeating "Command google returned: Error: [WinError 10060]" 

### Expected behavior 🤔

Succefully run.

### Your prompt 📝

```yaml
AI Name: ResearchGPT
ResearchGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
ResearchGPT is: an AI designed to autonomously search articles and write a paper of "abalone heterosis"
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1:  write a 1000 words article
Goal 2:  use latest articles
Goal 3: write like an expert
Goal 4: include citation information and reference list in the article
Goal 5:
Using memory of type: PineconeMemory
```
