### ISSUE TITLE
getting Traceback (most recent call last):   File "C:\Users\Spencer\Auto-GPT\scripts\main.py", line 361, in <module>     if command_name.lower() == "error":        ^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'lower' after latest update

### ISSUE THREAD

**Issue by Shyvadi** [Torantulino/Auto-GPT#534]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

run main.py

ask it to search something online

### Current behavior 😯

Errors with
Traceback (most recent call last):
  File "C:\Users\Spencer\Auto-GPT\scripts\main.py", line 361, in <module>
    if command_name.lower() == "error":
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

### Expected behavior 🤔

not erroring

### Your prompt 📝

```yaml
AI Name: Tommy-AI
Tommy-AI here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
Tommy-AI is: An AI designed to assist with gathering information
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Find information on "skylerellis.mp3"
Goal 2:
```
