### ISSUE TITLE
unknown command `FT.SEARCH` when using redis-stack-server docker container

### ISSUE THREAD

**Issue by bigsk1** [Torantulino/Auto-GPT#562]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

requirements.txt installed

password set in .env for redis

docker container started with $  docker run -d --name redis-stack-server -p 127.0.0.1:6379:6379 redis/redis-stack-server:latest redis-server --requirepass <password_is_set>

python3 scripts/main.py

when it is running noticed errors in cli

looking up error is recommened redis-search-server be installed to solve FT.SEARCH error but it is now deprecated
https://hub.docker.com/r/redislabs/redisearch

### Current behavior 😯

Error calling Redis search:  unknown command `FT.SEARCH`, with args beginning with: `auto-gpt`, `*=>[KNN 10 @embedding $vector AS vector_score]`, `RETURN`, `2`, `data`, `vector_score`, `SORTBY`, `vector_score`, `A`,

### Expected behavior 🤔

no errors shown

### Your prompt 📝

```yaml
ai_goals:
- Increase net worth
- Grow Twitter Account
- Develop and manage multiple businesses autonomously
ai_name: Jarvis
ai_role: an AI designed to autonomously develop and run businesses with the sole goal
  of increasing your net worth
```
